{
 "title": "SRF Meteo Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(meteo_version_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Current Hour", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Weather",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "meteo_symbol24_index{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "meteo_temperature_celsius{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_max_temperature_celsius{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_min_temperature_celsius{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Rainfall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "meteo_total_rainfall_millimeters{time_period=\"hourly\", instance=\"$instance\"} * 10",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_rain_probability_percentages{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_average_windspeed_kilometers_per_hour{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_average_gust_kilometers_per_hour{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_wind_direction_degrees{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_humidity_percentages{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_pressure_pascals{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunshine",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_sunshine_duration_minutes{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Fresh Snow",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_fresh_snow_millimeters{time_period=\"hourly\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Today", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Weather",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "meteo_symbol24_index{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_min_temperature_celsius{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_max_temperature_celsius{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_total_rainfall_millimeters{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_rain_probability_percentages{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_average_windspeed_kilometers_per_hour{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_average_gust_kilometers_per_hour{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_wind_direction_degrees{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sunrise and Sunset",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_sunrise_time{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_sunset_time{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Sun",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "meteo_sunshine_hours{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    },
    {
     "expr": "meteo_uv_index{time_period=\"daily\", instance=\"$instance\"}",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}